### ISSUE TITLE
Return EEG as contiguous array be default

### ISSUE THREAD

**Issue by zduey** [pennmem/ptsa_new#109]
In order to use MorletWaveletFilterCpp, the eeg data needs to be stored as a contiguous array in memory, i.e. doing something like np.ascontiguousarray(eeg.data) assuming eeg represents what is returned by eeg_reader.read(). I think this should be done by default during read() instead of requiring the user to figure out the error and do it themselves

**Comment by mivade** [comment]
@zduey what is an example of "the error"?

**Comment by mivade** [comment]
Closing since we're moving away from using PTSA to load data.
