### ISSUE TITLE
Loss of numpy append_field functionality

### ISSUE THREAD

**Issue by LoganJF** [pennmem/ptsa_new#117]
When events are loaded the old way using the matlab path, the events have functionality with the numpy function append_field. However, the new events loaded using json do not have this functionality and I'm not sure why. 
<img width="755" alt="screen shot 2018-01-11 at 5 37 25 pm" src="https://user-images.githubusercontent.com/29643765/34851004-20ef15ea-f6f6-11e7-8ad9-c1c70b1de6ec.png">

**Comment by LoganJF** [comment]
I'm currently using this as a work around
<img width="752" alt="screen shot 2018-01-11 at 5 47 22 pm" src="https://user-images.githubusercontent.com/29643765/34851332-91a98f80-f6f7-11e7-893f-8027dc5f74a6.png">

**Comment by mivade** [comment]
Possibly relevant: https://stackoverflow.com/a/42373715/6628184

**Comment by mivade** [comment]
@LoganJF can you upload these notebooks as a [gist](https://gist.github.com/) so that I can play around with this?

**Comment by LoganJF** [comment]
Okay I uploaded them (https://gist.github.com/LoganJF/034adbea7ef12a2e2e9871a12871e6da) can you view them?

**Comment by mivade** [comment]
Yes. Thanks!

**Comment by mivade** [comment]
The problem is that the `stim_params` field in the JSON events is itself a Python dict. This was a poor design choice when the JSON events were defined that we are now unfortunately stuck with. If you create a subset of events which omits `stim_params`, you can append fields without issues.

Example:

```python
ra = np.rec.array(json_events)
names = [name for name in ra.dtype.names if name not in ['stim_params']]
ra2 = ra[names]
append_fields(base=ra2, names='new_field', data=data_values, dtypes=ra2.mstime.dtype)
```

**Comment by mivade** [comment]
The best thing to do for now is document this behavior.

Closing in favor of #128.
