### ISSUE TITLE
Do not modify eegfile field by default

### ISSUE THREAD

**Issue by zduey** [pennmem/ptsa_new#122]
When the EventReader loads an event file, it automatically prepends the given "root" kwarg to every value in the "eegfile" field. The issue here is if you load some events, do some processing, save them, and then try to load them later from a computer that has a different mount point, this can causes issues locating the eegfile corresponding to each event. It would be better for anything that uses these fields to do the appending as needed without modifying the events themselves.

**Comment by mivade** [comment]
Closing since we're transitioning away from using PTSA for loading data.
