### ISSUE TITLE
Event files can not be read using BaseEventReader if they have not been aligned with EEG data

### ISSUE THREAD

**Issue by mivade** [pennmem/ptsa_new#15]
> Event files can not be read using BaseEventReader if they have not been aligned with EEG data. This constraint does not seem necessary.

**Comment by leondavis1** [comment]
This is not completely correct. This behavior is controlled by the `include_events_with_no_eeg` parameter, which is set to False by default.

The default behavior could be changed so as to read all events, and then it would be the responsibility of the user to exclude events events with no eeg when using events to load EEGs.

**Comment by nherweg** [comment]
I think you are referring to 'eliminate_events_with_no_eeg'. Regardless of whether that is set to True or False I get the error below when trying to read unaligned events as e.g. '/data/events/dBoy25/no_eegfile_field/FR434_events_sess0.mat'

AttributeErrorTraceback (most recent call last)
<ipython-input-4-cc3b043664c1> in <module>()
----> 1 events = BaseEventReader(filename='/data/events/dBoy25/no_eegfile_field/FR434_events_sess0.mat', use_reref_eeg = False, eliminate_events_with_no_eeg=False).read()
      2 events

/home1/nherweg/anaconda2/envs/getstarted/lib/python2.7/site-packages/ptsa/data/readers/BaseEventReader.pyc in read(self)
     97             return self.read_json()
     98         else:
---> 99             return self.read_matlab()
    100 
    101     def check_reader_settings_for_json_read(self):

/home1/nherweg/anaconda2/envs/getstarted/lib/python2.7/site-packages/ptsa/data/readers/BaseEventReader.pyc in read_matlab(self)
    160             data_dir_prefix = self.find_data_dir_prefix()
    161             for i, ev in enumerate(evs):
--> 162                 ev.eegfile = join(data_dir_prefix, str(pathlib.Path(str(ev.eegfile)).parts[1:]))
    163 
    164             evs = self.normalize_paths(evs)

/home1/nherweg/anaconda2/envs/getstarted/lib/python2.7/site-packages/numpy/core/records.pyc in __getattribute__(self, attr)
    251         else:
    252             raise AttributeError("'record' object has no "
--> 253                     "attribute '%s'" % attr)
    254 
    255     def __setattr__(self, attr, val):

AttributeError: 'record' object has no attribute 'eegfile'
