### ISSUE TITLE
xarray dependency

### ISSUE THREAD

**Issue by kahana-sysadmin** [pennmem/ptsa_new#239]
xarray version 0.14 has diverged sufficiently to cause problems. Dependency should be changed to xarray >=0.10,<0.14 until ptsa can be updated to be compatible with new xarray versions.

**Comment by ctw** [comment]
Ryan and I have already developed a fix which will be pushed with the next
ptsa update.

**Comment by jrudoler** [comment]
I'm currently using xarray 0.19, so this has clearly been fixed
