### ISSUE TITLE
Reading events using BaseEventReader from directories other than /data/events doesn't work.

### ISSUE THREAD

**Issue by nherweg** [pennmem/ptsa_new#38]
This includes e.g. /data/scalp_events. See below for error message:

/home1/nherweg/anaconda2/envs/getstarted/lib/python2.7/site-packages/ptsa/data/readers/BaseEventReader.pyc in find_data_dir_prefix(self)
    203         if not prefix:
    204             raise RuntimeError(
--> 205                 'Could not determine prefix from: %s using common_root: %s' % (self._filename, self.common_root))
    206 
    207         return find_dir_prefix(self._filename, self.common_root)

RuntimeError: Could not determine prefix from: /data/scalp_events/db2.5/LTP040_events.mat using common_root: data/events

**Comment by maciekswat** [comment]
BaseEventReader by default will do path-wrangling and this is what causes problems. There is a new CMLEventReader (which is based on BaseEventReader) that by default does not do any manipulation of paths so if you use it it should work. Simply replace BaseEventReader with CMLEventReader.
