### ISSUE TITLE
Allow specification of dtypes in MatlabIO

### ISSUE THREAD

**Issue by maciekswat** [pennmem/ptsa_new#45]
This is especially important when dealing with Matlab structs

**Comment by nherweg** [comment]
Are there any updates on this? Christoph and I just discussed, that alternatively, there could be an input argument to the EventReader that defines the dtype for every column.

**Comment by ctw** [comment]
I just pushed a fix to use all elements. We should also add the option of specifying the dtypes as indicated in my commit message.

**Comment by maciekswat** [comment]
We could do explicit type specification of columns. That's easiest. I still think events should come with metadata that contains type specification of columns. Buy most importantly I would ban Matlab   structs to be used as events. It is really bad solution 

_Sent from my Motorola Moto G (4) using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ctw** [comment]
That seems like a good solution once all matlab events have been converted to a new format.

**Comment by mivade** [comment]
Closing since Matlab events are considered deprecated.
