### ISSUE TITLE
tal_reader loads bipolar and monopolar files differently

### ISSUE THREAD

**Issue by smeisler** [pennmem/ptsa_new#46]
When I load a monopolar file into the tal_reader using the following syntax:

tal_path = '<tal_path>'
tal_reader = TalReader(filename=tal_path)
tal_structs = tal_reader.read()

I get the following error:

AttributeError: Could not read tal struct data. Try specifying struct_name argument :
TalReader(filename=e_path, struct_name=<name_of_struc_to_read>)

When I load a bipolar file into the tal_reader using the same syntax, it loads fine and does not require the second argument "struct_name".  What kind of object is the second argument supposed to be, and why is it only required for monopolar files?

I am on a Windows computer.

**Comment by maciekswat** [comment]
I think the problem might be in the underlying Matlab file you are trying to read. Normally Matlab file contains structure called ``bp_tal_struct`` and this is what ``TalReader`` expects to find. if for some reason the name of the structure is different you need to provide the name for it using ``struct_name`` argument.   So the reason you are experiencing this issue with monopolar files is that they do not have ``bp_tal_struct`` but rather store "monopolar structure" under different name instead. Open up this file in Matlab and check what it is. There might be still some inconsistency in the data

**Comment by smeisler** [comment]
I was able to load monopolar files using the struct_name ='talStruct'.  I feel it makes more sense to have an argument be "mono" or "bi", rather than requiring one to know the name of the struct within the matlab file.

**Comment by mivade** [comment]
@leondavis1 has this been fixed? Please close if so.
