### ISSUE TITLE
eeg_reader.read is "killed" when running in SSH

### ISSUE THREAD

**Issue by smeisler** [pennmem/ptsa_new#47]
I ran the code as instructed in the tutorial 

>>>eeg_reader = EEGReader(events=base_events, channels=monopolar_channels, start_time=0.0, end_time=1.6, buffer_time=1.0)
>>> base_eegs = eeg_reader.read()

With the events and channels previously defined by the BaseEventsReader and TalReader respectively.  The code begins to run, but after a while, the process stops, the word "Killed" is presented with no further error message, and Python is exited.  I tried this using PuTTY to SSH on to Rhino and I am on a Windows computer.

**Comment by maciekswat** [comment]
Do you get reasonable transfer speeds when you access rhino files via ssh on windows? I tried that and the speeds were horribly slow. I wonder if this is an issue. One thing you may try doing is downloading data for few subjects to your local drive and running it locally (this is what I do on Windows) while you develop your code. When you run your code your best bet is rhino. Let me know if the problem still persists after you download the data. What subject was it?

**Comment by smeisler** [comment]
The subject was R1111M for a FR1 event.  I uploaded the local files on my computer and the EEG reader ran fine.  I think the SSH transfer speeds were indeed the issue.

**Comment by mivade** [comment]
Closing this as it looks resolved.
