### ISSUE TITLE
Add support for float32

### ISSUE THREAD

**Issue by nherweg** [pennmem/ptsa_new#58]
Would it be possible to add support for data stored in single precision float format?

**Comment by mivade** [comment]
- Sample data: `/data/eeg/FR430/eeg.noreref/`
- Events: `/data/events/dBoy25/FR430_events_sess*.mat`

**Comment by nherweg** [comment]
Looking at the BaseRawReader, it seems like this has been implemented? Is that ready to be used?

**Comment by mivade** [comment]
It's ready to be tested. You can try it out by building from source (see [here](https://github.com/pennmem/ptsa_new#build-from-source) for instructions). If it works for you, we can make a new release this week.

**Comment by mivade** [comment]
Should be fixed in v1.1.2.
