### ISSUE TITLE
EEG Loading Questions

### ISSUE THREAD

**Issue by smeisler** [pennmem/ptsa_new#61]
1: The tutorial details how to load EEGs that represent the average across all events.  Is there a way to load all EEGs such that they represent one continuous time series with each event's time series appended to that before it?

2:  Is there a way, similar to the old Matlab toolbox when specifying 0 as the EEG end time, to default load the entire duration of the EEG?  If not, is there a way to get obtain the maximum time that could be loaded from a set of events?

**Comment by smeisler** [comment]
A few other questions I have related to loading EEGS
3: I am trying to reduce the memory and time required to load long, multi-electrode timeseries using the EEG reader by downsampling by a factor of 2. While I can downsample after the EEG is loaded, that still requires that the large timeseries is operated on. Would indexing or slicing into the base events be the right way to go about this?

4: If I want to load a bipolar EEG, is it necessary to load all monopolar channels before mapping to bipolar (like in the tutorial)? Or is it possible to only load the channels being used.

**Comment by ctw** [comment]
Perhaps this is helpful (they seem to have solved the issue of visualizing long time series):
https://github.com/OpenElectrophy/OpenElectrophy/blob/master/OpenElectrophy/gui/viewers/signalviewer.py

**Comment by smeisler** [comment]
Unfortunately, this uses matplotlib while I'm employing pyqtgraph as my plotting library, so I won't be able to use this code as is, though I can see if some of the concepts can be adapted to pyqtgraph.  Thank you.
