### ISSUE TITLE
Problems with BaseRawReader

### ISSUE THREAD

**Issue by smeisler** [pennmem/ptsa_new#64]
I'm using the BaseRawReader to gather EEG signals to plot, but the output from the reader is not a TimeSeriesX, which is giving me trouble plotting and filtering (since the filters expect TimeSeriesX objects).

**Comment by maciekswat** [comment]
Try this:

get an array of events (any events for the session you want to analyze), extract core name of the eeg file - `dataroot`, and then use EEGReader with `session_dataroot=dataroot` passed as one of its arguments

```python
session = evs[0].session
dataroot = base_events[base_events.session == session][0].eegfile
session_reader = EEGReader(session_dataroot=dataroot, channels=monopolar_channels)
session_eegs = session_reader.read()
```
see also:

https://pennmem.github.io/ptsa/examples/classifier_time_series.html
l

**Comment by maciekswat** [comment]
@smeisler : can we close this issue?

**Comment by smeisler** [comment]
Yes, as the EEGReader serves the purpose I was trying to achieve.
