### ISSUE TITLE
Outdated classifier tutorial

### ISSUE THREAD

**Issue by mgorenstein** [pennmem/ptsa_new#65]
I am attempting to replicate [this tutorial](https://github.com/pennmem/ptsa_new/blob/master/docs/examples/classifier_time_series.ipynb) on rhino.
 
However, the `compute_features_recalls_normalization_params` function depends on `from ptsa.data.common import xr`, and `xr` is no longer a module in ptsa. 

Is an updated tutorial or code sample available elsewhere?

Thanks.

**Comment by mivade** [comment]
`xr` is the standard way to import `xarray`:

```
import xarray as xr
```

As far as I know there isn't an updated version of this, but it could definitely use some cleanup.

**Comment by mgorenstein** [comment]
@mivade ... thanks for the suggestion. I'll make that replacement and check whether the remainder of the tutorial is still accurate. 

The minimum code example that would be useful to me would:
1. Load all of a single subject's sessions using the appropriate jsonindex/ptsa readers
2. Partition word-events into the two classifier classes
3. Apply wavelet decomposition to all events
4. Train classifier and test on left out session
5. Output AUC

**Comment by mivade** [comment]
I'm working on an updated version using CMLReaders. Closing this in favor of pennmem/cmlreaders#128.
