### ISSUE TITLE
Problems installing PTSA

### ISSUE THREAD

**Issue by seqasim** [pennmem/ptsa_new#7]
Hi Maciek,

This is Salman Qasim from Josh Jacob's lab. 

I have finally gotten around to setting up PTSA on Rhino so I can transition all my analyses to Python. While installing PTSA, I run into the following error:

g++ -pthread -shared -L/home1/salman.qasim/.conda/envs/my_root/lib -Wl,-rpath=/home1/salman.qasim/.conda/envs/my_root/lib,--no-as-needed -fPIC -O3 -fPIC -O3 build/temp.linux-x86_64-2.7/home1/salman.qasim/Salman_Python_Scripts/PTSA_GIT/ptsa_new/ptsa/extensions/morlet/morlet.o build/temp.linux-x86_64-2.7/home1/salman.qasim/Salman_Python_Scripts/PTSA_GIT/ptsa_new/ptsa/extensions/morlet/MorletWaveletTransformMP.o build/temp.linux-x86_64-2.7/home1/salman.qasim/Salman_Python_Scripts/PTSA_GIT/ptsa_new/ptsa/extensions/morlet/morlet_wrap.o -L/home1/salman.qasim/Salman_Python_Scripts/PTSA_GIT/ptsa_new/build/third_party_install/lib -L/home1/salman.qasim/.conda/envs/my_root/lib -lfftw3 -lpython2.7 -o build/lib.linux-x86_64-2.7/ptsa/extensions/morlet/_morlet.so
/usr/bin/ld: /home1/salman.qasim/.conda/envs/my_root/lib/libfftw3.a(mapflags.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC

/home1/salman.qasim/.conda/envs/my_root/lib/libfftw3.a: could not read symbols: 

Bad value

collect2: error: ld returned 1 exit status

error: command 'g++' failed with exit status 1

Can you help with this? I really don't know what the issue might be.

**Comment by mivade** [comment]
Hi Salman,

Did you ever resolve this issue? I just overhauled the installation so that it should be much easier.

**Comment by seqasim** [comment]
Hey Mike,

I had not. I will try with the new installation today - thanks!!
