### ISSUE TITLE
JsonIndexReader crashes if anything is registered before events

### ISSUE THREAD

**Issue by leondavis1** [pennmem/ptsa_new#86]
If a subject is missing their "experiments" field in the index, the reader crashes.

**Comment by mivade** [comment]
Example with traceback?

**Comment by leondavis1** [comment]
![indexreader_traceback](https://user-images.githubusercontent.com/8563958/33500008-461b0dea-d6a5-11e7-8a6e-cea262917b99.jpg)

**Comment by leondavis1** [comment]
This is the file that I used to produce the error

[r1.json.txt](https://github.com/pennmem/ptsa_new/files/1522832/r1.json.txt)

**Comment by mivade** [comment]
@leondavis1  is this still relevant?
