### ISSUE TITLE
EEG reader should not modify events when calling .read()

### ISSUE THREAD

**Issue by zduey** [pennmem/ptsa_new#95]
Right now, when you create an EEGReader and call the read() method, there are occasions where 'bad' events are removed. This is done without notifying the user. The way to check if any bad events were removed is to check the return value of eeg.removed_bad_data(). This seems sub-optimal to me since you need to know this magic is happening to know that you need to call this method. Instead, would it make sense to add a kwarg called remove_bad_events. The default can be True to avoid changing code that currently relies (perhaps unknowingly) on this being done.

**Comment by mivade** [comment]
At the very least this should raise a warning.
